[theme]
primaryColor = "#00AEEF"
backgroundColor = "#0A192F"
secondaryBackgroundColor = "#112240"
textColor = "#E6F1FF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
